name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

env:
  PUBLIC_API_URL: https://api.arthurplazanet.com

jobs:
  lint_format:
    if: ${{ ! startsWith(github.event.pull_request.head.ref, 'renovate/') }}
    name: Lint, Format and build - Node version 22
    uses: ./.github/workflows/lint_format.yml
    with:
      node_version: 22

  build:
    if: ${{ ! startsWith(github.event.pull_request.head.ref, 'renovate/') }}
    uses: ./.github/workflows/build.yml
    with:
      node_version: 22
      PUBLIC_API_URL: ${{ env.PUBLIC_API_URL }}
